repos:
  - repo: git@github.maicoin.site:maiami/pre-commit.git # fork from https://github.com/gruntwork-io/pre-commit
    rev: v0.1.16 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      #- id: terraform-fmt
      - id: terraform-validate # export VAULT_ADDR=localhost to pass validation
      - id: terragrunt-hclfmt
      #- id: tflint
      - id: shellcheck
      #- id: gofmt
      #- id: golint

  - repo: git@github.maicoin.site:maiami/pre-commit-terraform.git
    rev: v1.72.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      #- id: terraform_checkov
      #  args:
      #    - --args=--skip-check CKV_SECRET_6 # FIXME false alarm on non-secret string
      #- id: terraform_docs
      #- id: terragrunt_validate
      #- id: terrascan
      #- id: terraform_tflint
      #- id: terraform_tfsec
      #- id: infracost_breakdown
      #- id: tfupdate
      #- id: terraform_wrapper_module_for_each
