---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: helm-repo
    role: runner
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - name: runner
    image: 335904908860.dkr.ecr.ap-southeast-1.amazonaws.com/jenkins/terraform-agent:1.2.2-2022-23
    tty: true
    command: ['tail', '-f', '/etc/hosts']
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      readOnlyRootFilesystem: false
    resources:
      limits:
        cpu: 1
        memory: 500M
      requests:
        cpu: 1
        memory: 500M
